# Generated by Django 2.0.5 on 2018-05-08 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=300)),
                ('zipcode', models.CharField(max_length=10)),
                ('primary_address', models.CharField(max_length=100)),
                ('secondary_address', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Address'),
        ),
    ]
