# Generated by Django 2.0.5 on 2018-05-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180509_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoptype',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DRAFT', 'DRAFT')], default='DRAFT', max_length=5),
        ),
    ]
