# Generated by Django 2.0.5 on 2018-05-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_shoptype_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('DENIED', 'DENIED'), ('ARCHIVED', 'ARCHIVED')], default='PENDING', max_length=8),
        ),
    ]
