# Generated by Django 2.0.5 on 2018-05-09 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_advertisement_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='address1',
            field=models.CharField(default='Hello', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='latitude',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='longitude',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='state',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='zipcode',
            field=models.CharField(default=22, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
