# Generated by Django 2.0.5 on 2018-05-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180509_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='address1',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='latitude',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='longitude',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
