# Generated by Django 2.0.5 on 2018-05-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180509_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoptype',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DRAFT', 'DRAFT')], default='DRAFT', max_length=6),
        ),
    ]
