# Generated by Django 2.0.5 on 2018-05-19 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_advertisement_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
