# Generated by Django 2.0.5 on 2018-05-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_delete_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[(1, 'APPROVED'), (2, 'PENDING'), (3, 'DENIED'), (4, 'ARCHIVED')], default=2, max_length=8),
        ),
    ]
