# Generated by Django 2.0.5 on 2018-05-29 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20180526_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adimage',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Advertisement'),
        ),
    ]
