# Generated by Django 2.0.5 on 2018-05-29 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20180529_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adimage',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Advertisement'),
        ),
    ]
