# Generated by Django 2.0.6 on 2018-06-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20180529_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='closed_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='open_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
