# Generated by Django 2.0.6 on 2018-06-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20180620_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('DENIED', 'DENIED'), ('ARCHIVED', 'ARCHIVED')], default='PENDING', max_length=8),
        ),
    ]
