# Generated by Django 2.0.6 on 2018-06-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20180629_0747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
