# Generated by Django 2.0.6 on 2018-06-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20180629_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adimage',
            name='file',
            field=models.ImageField(upload_to='classifieds'),
        ),
    ]
