# Generated by Django 2.0.7 on 2018-07-08 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20180630_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='shop_type',
        ),
    ]
