# Generated by Django 2.0.7 on 2018-07-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_remove_category_shop_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shoptype',
        ),
        migrations.AddField(
            model_name='category',
            name='fa_icon',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
