# Generated by Django 2.0.7 on 2018-07-15 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20180715_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', related_query_name='advertisement', to='products.Subcategory'),
        ),
    ]
